version: '3.7'

services:
  blog:
    image: docker.zivili.ch/gbili/node-app-js:0.0.1
    environment:
      APP_DIRNAME: blog
      VIRTUAL_HOST: guillermo.at
      LETSENCRYPT_HOST: guillermo.at
      LETSENCRYPT_EMAIL: mail@guillermo.at
    volumes:
      - node-apps:/node-server
    restart: always

volumes:
  node-server:
    external:
      name: git-server-hooks_node-apps


networks:
    default:
        external:
            name: nginx-proxy